{{
    config(
        materialized='table'
    )
}}

WITH SNAPSHOT_TABLE AS (
SELECT  300 +row_number() OVER (ORDER BY ID) AS USER_KEY ,* FROM {{ ref('USER') }}
)
SELECT  50000+row_number() OVER (ORDER BY ID) AS USER_KEY,ID AS USER_ID,USERNAME AS USER_NAME,FIRSTNAME,DEPARTMENT,CITY,DBT_VALID_FROM
         AS EFFECTIVE_FROM ,DBT_VALID_TO AS EFFECTIVE_TO,
         (CASE WHEN ST.DBT_VALID_TO IS NULL THEN 'TRUE' ELSE 'FALSE' END) AS STATUS
          FROM SNAPSHOT_TABLE ST
          


